### ISSUE TITLE
AMQP message subject

### ISSUE THREAD

**Issue by kradalby** [kradalby/okse#127]
AMQP has a message subject.

When it is from a AMQP sender, what should we do with it?
When it is from another protocol, what should we populate it with? Nothing is an option.

Now, the subject from okse is populated with the message id.

**Comment by mythern** [comment]
I think that for intra AMQP messaging, things should behave normally.
For AMQP to OKSE, it is hard to say as we do not know how other applications are intended to use the messages. If the AMQP content is pure XML, adding the subject as an additional structure might break things. It could be inserted as a SOAP header, or it could just be ignored, focusing on the message content.

For OKSE to AMQP, using the message ID does not mean anything insightful, as it is just a random hash and not embedded in WSN for example. Hence, it would be better to just indicate that the message is a OKSE Translated Message or something.

**Comment by freboto** [comment]
This was hard work, but i got it in the end. Hard coded a subject to indicate that the message is translated from a OKSE message.
