### ISSUE TITLE
Reduce log output from AJAX calls

### ISSUE THREAD

**Issue by mythern** [kradalby/okse#50]
See the logs when browsing the tabs, its quite much.

**Comment by hakloev** [comment]
This will of course be done. It's there on purpose. It's a temporary thing I have done for debug reasons and chosen not to remove before after I know for a fact that some of the methods in the controller-classes are completely correct.

**Comment by mythern** [comment]
And i am just creating issues so i dont forget about the stuff that i think about in the evenings... :beers:

**Comment by hakloev** [comment]
I see :) There should be an "like"-button on comments here, haha

**Comment by hakloev** [comment]
Done!
