### ISSUE TITLE
Make okse.log the default log view file

### ISSUE THREAD

**Issue by mythern** [kradalby/okse#51]
As the title says

**Comment by kradalby** [comment]
This is based on when the application finds the initial files in the directory. I would have thought it would use lexicographical order, but it seem kinda random. OS X took okse first, while Debian takes spring.

**Comment by mythern** [comment]
That does not matter. The log output filename of the desired default is known, so i don't really see the issue with making that work.

**Comment by kradalby** [comment]
> On 21 Apr 2015, at 19:00, mythern <notifications@github.com> wrote:
> 
> That does not matter. The log output filename of the desired default is known, so i don't really see the issue with making that work.
> 
> 
The user is allowed to change the name of the logs through the log config.

**Comment by mythern** [comment]
Ah, you moved the config outside the scope of the classpath, i see. Well that makes things more complicated, yes.

**Comment by mythern** [comment]
A partial workaround could be to just check if "okse.log" exists in the logs folder, use that as default, otherwise, it just uses the default behaviour.

**Comment by hakloev** [comment]
```
files.forEach(f -> {
            if (!fileNames.containsValue(f.getName())) {
                if (f.getName().equalsIgnoreCase("okse.log")) {
                    fileNames.put(0, f.getName());
                } else {
                    fileNames.put(fileID++, f.getName());
                }
            }
        });
```

Quick and dirty hack..
