### ISSUE TITLE
Make log view a bit prettier

### ISSUE THREAD

**Issue by mythern** [kradalby/okse#52]
Create some class for the `<pre>` element that removes borders and border-radius, lighten the background color etc. Also take a look at button style, spacing, gaps etc.

**Comment by hakloev** [comment]
I assign myself to it, and will fix this while I fix the line spacing on the buttons..

**Comment by hakloev** [comment]
Same comment as in issue #49.

**Comment by mythern** [comment]
Fixed by @hakloev
