### ISSUE TITLE
Do we need to rethink the layout and presentation of the Topics pane in web admin?

### ISSUE THREAD

**Issue by mythern** [kradalby/okse#55]
Problem areas:

* What happens when there are 100 topics in the system? or 500?
* Same goes for subscribers.

The goal must be to have a compact but detailed enough representation of topics and subscribers.

**Comment by hakloev** [comment]
This was a part of our initial discussions, and then we agreed upon doing things as they are now. But for all things sake, I'm open for discussing this over. I agree that the problem areas you suggest are of such an importance that we need to take them into consideration.  Does anyone have a suggestion on how this could be solved efficiently?

**Comment by mythern** [comment]
The only easy to implement and viable option here is a paginated table imo. With a search field using typeahead or something as support. But instead of using an actual table, we could create a specialized table-like component with divs and css.

**Comment by hakloev** [comment]
Can I consider this closed now?
